### PR TITLE
move R files to a folder

### PR DESCRIPTION
**Pull request by jonjunduan**
Just a simple operation of moving R files to the r folder

### CODE REVIEW

**Comment by stephhazlitt** [comment]
@jonjunduan you may want to make this PR against the `dbt` branch to avoid merge conflicts. I would include a very concise readme in this folder that documents what the software needed to run the scripts, what the scripts do and order/what to run. Does the `utils` folder live with this code? Last, I suggest `r-implementation` might be more informative folder name and avoid any confusion with the common practice of have an `R` folder for source files?

**Comment by lindsay-fredrick** [comment]
Looks like Steph beat me to it, with essentially the same comments I would have. I would suggest having a look at the new dbt README and making something similar for the R files folder (whatever it ends up being named). Then the main README can point to the different folders and explain the differences in implementations.

**Comment by jonjunduan** [comment]
Update the r folder name and readme in the r folder.

**Review by lindsay-fredrick — APPROVED** [review]
I think the new readme and R folder look good now - I'm just worried that sending this to the dbt branch (while it was originally branched off main I assume) is creating a lot of conflicts now, and we don't want to overwrite any of the changes we just made.

**Pull request merged**
